[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["corepack enable", "corepack prepare pnpm@latest --activate", "pnpm install --filter @pulze/bot"]

[phases.build]
cmds = ["pnpm --filter @pulze/bot build"]

[start]
cmd = "cd apps/bot && node dist/app.js"
