[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm install -g pnpm@8.15.0 && pnpm install"]

[phases.build]  
cmds = ["pnpm run build:bot"]

[start]
cmd = "node apps/bot/dist/app.js"
