[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g pnpm@9",
  "pnpm install"
]

[phases.build]
cmds = ["pnpm --filter @pulze/bot build"]

[start]
cmd = "node apps/bot/dist/app.js"
